---
roles:
  pe-puppet-master:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    providers:
      - type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 4096]
    provisioners:
      - type: hosts
      - type: shell
        inline: |
            firewall-cmd --permanent --zone=public --add-service=https
            firewall-cmd --permanent --zone=public --add-port=8140/tcp
            firewall-cmd --permanent --zone=public --add-port=61613/tcp
            firewall-cmd --reload
            mkdir -p /root/.ssh
            cp -f /vagrant/ssh-keys/* /root/.ssh
            chmod 0600 /root/.ssh/id_rsa
            rm -f /etc/ssl/certs/ca-bundle.crt
            yum -y install ca-certificates
      - type: pe_bootstrap
        answer_extras:
          - 'q_puppetmaster_r10k_remote=git@gitlab:puppet/control.git'
          - 'q_puppetmaster_r10k_private_key=/root/.ssh/id_rsa'
        role: !ruby/sym master
  pe-puppet-agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap}
  gitlab-server:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    providers:
      - type: virtualbox
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 1024]
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap}
      - type: shell
        inline: |
            firewall-cmd --permanent --zone=public --add-service=http
            firewall-cmd --permanent --zone=public --add-service=https
            firewall-cmd --reload
            yum -y install curl postfix rubygems git gcc mysql-devel ruby-devel
            systemctl enable postfix
            systemctl start postfix
            curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | bash
            yum -y install gitlab-ce
            gitlab-ctl reconfigure
            gem install gitlab
            gitlab-rails r -e production /vagrant/scripts/set-gitlab-password.rb
            export GITLAB_API_ENDPOINT=http://gitlab/api/v3
            export GITLAB_API_PRIVATE_TOKEN="$(gitlab-rails r -e production /vagrant/scripts/get-gitlab-token.rb)"
            export PUB_KEY="$(cat /vagrant/ssh-keys/id_rsa.pub)"
            gitlab create_ssh_key 'root@master' "$PUB_KEY"
            gitlab create_group 'puppet' 'puppet'
            export GITLAB_NAMESPACE_ID=$(gitlab groups | grep puppet | awk '{ print $5 }')
            gitlab create_project "control" "{namespace_id: '$GITLAB_NAMESPACE_ID'}"
            gitlab create_project "helloworld" "{namespace_id: '$GITLAB_NAMESPACE_ID'}"
            git config --global user.name "root"
            git config --global user.email "root@master"
            mkdir -p /root/.ssh
            ssh-keyscan gitlab >> ~/.ssh/known_hosts
            cp -f /vagrant/ssh-keys/* /root/.ssh
            chmod 0600 /root/.ssh/id_rsa
            tar xf /vagrant/git/control.tar -C /tmp
            tar xf /vagrant/git/helloworld.tar -C /tmp
            cd /tmp/control
            git push -u origin production
            cd /tmp/helloworld
            git push -u origin master
